[tools]
atuin = "18.10.0"
bat = "0.26.1"
bottom = "0.12.3"
bun = "1.3.5"
delta = "0.18.2"
dust = "1.2.4"
eza = "0.23.4"
fd = "10.3.0"
fzf = "0.67.0"
go = "1.25.5"
jq = "1.8.1"
node = "24.12.0"
python = "3.14.2"
ripgrep = "15.1.0"
starship = "1.24.2"
usage = "2.16.1"
uv = "0.9.21"
yq = "4.52.2"
zoxide = "0.9.8"