[tools]
atuin = "latest"
bun = "latest"
go = "latest"
node = "lts"
python = "3.14"
ripgrep = "latest"
uv = "latest"
fd = "latest"
starship = "latest"
bat = "latest"
eza = "latest"
zoxide = "latest"
fzf = "latest"
